# Generated by Django 4.2.2 on 2023-07-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Razorpay', 'Razorpay'), ('Wallet', 'Wallet')], max_length=100),
        ),
    ]
