# Generated by Django 4.2.2 on 2023-06-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_productvariant_stock_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
