# Generated by Django 4.2.2 on 2023-07-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
