# Generated by Django 4.2.2 on 2023-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='pdt_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
