# Generated by Django 4.2.2 on 2023-07-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_productvariant_pdt_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
