# Generated by Django 4.2.2 on 2023-07-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
