# Generated by Django 4.2.2 on 2023-07-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_coupon'),
        ('cart', '0009_remove_cartitem_coupon_total_cart_cart_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ManyToManyField(to='payment.coupon'),
        ),
    ]
