# Generated by Django 4.2.2 on 2023-07-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_cart_coupon_cart_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupon',
            new_name='coupons',
        ),
    ]
