# Generated by Django 4.2.2 on 2023-07-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_coupon'),
        ('cart', '0011_rename_coupon_cart_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupons',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_coupon', to='payment.coupon'),
        ),
    ]
