# Generated by Django 4.2.2 on 2023-07-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelorder',
            name='cancel_reason',
            field=models.CharField(choices=[('Wrong Size', 'Wrong Size'), ('Other reasons', 'Other reasons')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('New', 'New'), ('out for shipping', 'out for shipping'), ('pending', 'pending'), ('delivered', 'delivered'), ('processed', 'processed')], default='New', max_length=100),
        ),
    ]
