# Generated by Django 4.2.2 on 2023-06-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('out for shipping', 'out for shipping'), ('canceled', 'canceled'), ('processed', 'processed'), ('pending', 'pending')], default='New', max_length=100),
        ),
    ]
