# Generated by Django 4.2.2 on 2023-07-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('out for shipping', 'out for shipping'), ('delivered', 'delivered'), ('canceled', 'canceled'), ('New', 'New')], default='New', max_length=100),
        ),
    ]
