# Generated by Django 4.2.2 on 2023-07-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_razorpay_order_id'),
        ('order', '0006_orderitem_user_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_color',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payment_details', to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('delivered', 'delivered'), ('canceled', 'canceled'), ('out for shipping', 'out for shipping'), ('pending', 'pending'), ('processed', 'processed')], default='New', max_length=100),
        ),
    ]
