# Generated by Django 4.2.2 on 2023-07-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_orderitem_product_color_alter_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('New', 'New'), ('delivered', 'delivered'), ('canceled', 'canceled'), ('processed', 'processed'), ('out for shipping', 'out for shipping')], default='New', max_length=100),
        ),
    ]
