# Generated by Django 4.2.2 on 2023-07-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_product_slug'),
        ('order', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.productcolor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out for shipping', 'out for shipping'), ('New', 'New'), ('delivered', 'delivered'), ('canceled', 'canceled'), ('processed', 'processed')], default='New', max_length=100),
        ),
    ]
