# Generated by Django 4.2.2 on 2023-07-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderitem_product_color_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('out for shipping', 'out for shipping'), ('delivered', 'delivered'), ('processed', 'processed'), ('pending', 'pending'), ('canceled', 'canceled')], default='New', max_length=100),
        ),
    ]
