# Generated by Django 4.2.2 on 2023-07-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'processed'), ('delivered', 'delivered'), ('pending', 'pending'), ('out for shipping', 'out for shipping'), ('New', 'New'), ('canceled', 'canceled')], default='New', max_length=100),
        ),
    ]
