# Generated by Django 4.2.2 on 2023-07-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'processed'), ('New', 'New'), ('out for shipping', 'out for shipping'), ('delivered', 'delivered'), ('canceled', 'canceled'), ('pending', 'pending')], default='New', max_length=100),
        ),
    ]
