# Generated by Django 4.2.2 on 2023-07-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('out for shipping', 'out for shipping'), ('canceled', 'canceled'), ('delivered', 'delivered'), ('processed', 'processed'), ('New', 'New'), ('pending', 'pending')], default='New', max_length=100),
        ),
    ]
