# Generated by Django 4.2.2 on 2023-07-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('out for shipping', 'out for shipping'), ('canceled', 'canceled'), ('processed', 'processed'), ('delivered', 'delivered'), ('pending', 'pending')], default='New', max_length=100),
        ),
    ]
