# Generated by Django 4.2.2 on 2023-07-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('delivered', 'delivered'), ('canceled', 'canceled'), ('processed', 'processed'), ('pending', 'pending'), ('out for shipping', 'out for shipping')], default='New', max_length=100),
        ),
    ]
