# Generated by Django 4.2.2 on 2023-07-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_status_cancelorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelorder',
            name='cancel_reason',
            field=models.CharField(choices=[('Wrong Size', 'Wrong Size'), ('Other reasons', 'Other reasons')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('pending', 'pending'), ('canceled', 'canceled'), ('out for shipping', 'out for shipping'), ('New', 'New'), ('processed', 'processed')], default='New', max_length=100),
        ),
    ]
