# Generated by Django 4.2.2 on 2023-07-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_cancelorder_cancel_reason_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelorder',
            name='cancel_reason',
            field=models.CharField(choices=[('Other reasons', 'Other reasons'), ('Wrong Size', 'Wrong Size')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('processed', 'processed'), ('canceled', 'canceled'), ('pending', 'pending'), ('out for shipping', 'out for shipping'), ('New', 'New')], default='New', max_length=100),
        ),
    ]
