# Generated by Django 4.2.2 on 2023-07-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('out for shipping', 'out for shipping'), ('canceled', 'canceled'), ('pending', 'pending'), ('New', 'New'), ('processed', 'processed'), ('delivered', 'delivered')], default='New', max_length=100),
        ),
    ]
