# Generated by Django 4.2.2 on 2023-07-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('out for shipping', 'out for shipping'), ('pending', 'pending'), ('processed', 'processed'), ('canceled', 'canceled'), ('New', 'New'), ('delivered', 'delivered')], default='New', max_length=100),
        ),
    ]
