# Generated by Django 4.2.2 on 2023-07-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelorder',
            name='cancel_reason',
            field=models.CharField(choices=[('Wrong Size', 'Wrong Size'), ('Other reasons', 'Other reasons')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('out for shipping', 'out for shipping'), ('delivered', 'delivered'), ('processed', 'processed'), ('New', 'New'), ('canceled', 'canceled'), ('pending', 'pending')], default='New', max_length=100),
        ),
    ]
