# Generated by Django 4.2.2 on 2023-07-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_cancelorder_cancel_reason_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('processed', 'processed'), ('New', 'New'), ('canceled', 'canceled'), ('pending', 'pending'), ('out for shipping', 'out for shipping')], default='New', max_length=100),
        ),
    ]
